# Generated by Django 5.1.4 on 2024-12-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(null=True)),
                ('image', models.URLField(null=True)),
                ('link', models.URLField(null=True)),
                ('store', models.CharField(max_length=128)),
            ],
        ),
    ]
