# Generated by Django 5.1.4 on 2025-01-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_remove_product_description_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField()),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(null=True)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
