# Generated by Django 5.1.4 on 2025-01-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
